In [4]:
import numpy as np
import sys

The Basics

In [5]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#to get dimensions 
a.ndim

1

In [8]:
b.ndim

2

In [9]:
#to get the shape
b.shape

(2, 3)

In [10]:
a.shape

(3,)

In [11]:
#to get the type
a.dtype

dtype('int64')

In [12]:
#to get the item size
a.itemsize

8

In [13]:
#to get the total size(no. of elements in the array)
a.nbytes

24

Accessing/Changing specific elements,rows, columns etc

In [14]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
#to get a specific element [r,c]
a[1,5]

np.int64(13)

In [16]:
#to get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[:,2]

array([ 3, 10])

In [18]:
# [startindex:endindex:stepsize]
a[0,1:6:1]

array([2, 3, 4, 5, 6])

In [19]:
a[1,5]=20
print(a)

a[:,2]=2
print(a)

a[:,2]=[1,3]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  2  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  3 11 12 20 14]]


3d example


In [20]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
#to get specific element (work outside in )
c[:,1,1]

array([4, 8])

In [22]:
#replace
c[0,1,1]=4
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
c[:,0,:]=[[4,5],[3,4]]
print(c)

[[[4 5]
  [3 4]]

 [[3 4]
  [7 8]]]


Initializing Different Types of Arrays


In [24]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#all ones matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#any other no. matrix
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [27]:
#ant other no. (fll like)(gives shape according to the array stores in variale )
np.full_like(a,4)  

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
np.random.rand(2,3)

array([[0.54715664, 0.25005373, 0.4811237 ],
       [0.02520005, 0.15610869, 0.37197154]])

In [29]:
#random integer values
np.random.randint(7,size=(3,3))

array([[5, 4, 5],
       [1, 1, 2],
       [1, 4, 5]], dtype=int32)

In [30]:
#identitiy matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#to repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


example to creare an array

In [32]:
d=np.zeros((5,5))
d[0,:]=1
d[:,0]= 1
d[4,:]=1
d[:,4]=1
d[2,2]=9

print(d)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


or

In [33]:
arr=np.ones((5,5))
print(arr)
z=np.zeros((3,3))
z[1,1]=9
print(z)
arr[1:-1,1:-1]=z
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
#to be carefull while copying arrays

a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


Mathematics

In [35]:
a=np.array([1,2,3,4])
a*2

array([2, 4, 6, 8])

In [36]:
a+2

array([3, 4, 5, 6])

In [37]:
a*2

array([2, 4, 6, 8])

In [38]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [39]:
a**2

array([ 1,  4,  9, 16])

In [40]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [43]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
#to find the determinant
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

Statistics

In [47]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.min(stats,axis=0)

array([1, 2, 3])

In [57]:
np.max(stats,axis=1)

array([3, 6])

In [58]:
np.sum(stats)

np.int64(21)

Reorganising arrays

In [62]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Vertically stacking Vectors

In [64]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
#horinzontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

Load the data from File

In [76]:
filedata=np.genfromtxt("data.txt",delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[83, 27, 59, 14, 92,  6, 38, 71, 45, 11, 64],
       [33, 97, 19, 52, 76,  3, 88, 24, 67, 40,  9],
       [31, 56, 21, 85, 13, 70, 99,  5, 62, 47, 36],
       [18, 93, 28,  8, 50, 66, 74,  1, 43, 35, 60],
       [15, 90, 12,  7, 26, 98, 53, 20, 39,  2, 84],
       [30, 58, 25, 95,  4, 37, 48, 16, 55, 79, 22]], dtype=int32)

Boolean Masking and Advanced Indexing

In [77]:
filedata>50

array([[ True, False,  True, False,  True, False, False,  True, False,
        False,  True],
       [False,  True, False,  True,  True, False,  True, False,  True,
        False, False],
       [False,  True, False,  True, False,  True,  True, False,  True,
        False, False],
       [False,  True, False, False, False,  True,  True, False, False,
        False,  True],
       [False,  True, False, False, False,  True,  True, False, False,
        False,  True],
       [False,  True, False,  True, False, False, False, False,  True,
         True, False]])

In [78]:
filedata[filedata>50]

array([83, 59, 92, 71, 64, 97, 52, 76, 88, 67, 56, 85, 70, 99, 62, 93, 66,
       74, 60, 90, 98, 53, 84, 58, 95, 55, 79], dtype=int32)

In [79]:
#ypu can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])